project_id = "rapxqrjhrehfhqsafovf"

[functions.parse-sleep]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.suggest-tags]
verify_jwt = false

[functions.analyze-cover]
verify_jwt = false
